name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Baixa e instala a última versão do ChromeDriver
      - name: Install Latest ChromeDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -Lo /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          echo "ChromeDriver version installed: $LATEST_CHROMEDRIVER_VERSION"

      # Instala o Google Chrome correspondente ao ChromeDriver instalado
      - name: Install Compatible Google Chrome
        run: |
          CHROME_MAJOR_VERSION=$(chromedriver --version | grep -oP '\d+' | head -1)
          echo "Using Chrome major version: $CHROME_MAJOR_VERSION"
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=$CHROME_MAJOR_VERSION.*

      # Define o caminho do ChromeDriver como variável de ambiente
      - name: Set ChromeDriver path
        run: echo "CHROMEWEBDRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Run Coverage
        env:
          DISPLAY: :99.0
        run: |
          coverage run -m unittest discover tests
          coverage report -m
